#pragma once

#include <SDL2/SDL.h>
#include <stdlib.h>
#include "map.h"

// Maps as edited and generated by slev

#define MAJ_VER 0
#define MIN_VER 1

typedef struct {
    int height;
    SDL_Color color;
} Slev_Map_Point;

typedef struct {
    int version_major;
    int version_minor;
    Slev_Map_Point* map;
    int w, h;
} Slev_Map;

Slev_Map* slev_map_from_hc_maps(Map* color_map, Map* height_map, int w, int h);
Slev_Map_Point slev_map_get_coords(Slev_Map* map, int x, int y);
void slev_map_free(Slev_Map* map);
